### ISSUE TITLE
Configuration to disable spans for fields

### ISSUE THREAD

**Issue by kand617** [ravilushqa/otelgqlgen#129]
It seems like we currently create new spans for each field. Is there a way to turn this off?

**Comment by ravilushqa** [comment]
@Tochemey, yes. You can view details in this [PR](https://github.com/ravilushqa/otelgqlgen/pull/137).
I believe this ticket could be closed. What do you think?
CC @kand617

**Comment by kand617** [comment]
Perfect thanks!
