### ISSUE TITLE
Span status should be set to Ok or error

### ISSUE THREAD

**Issue by dkrizic** [ravilushqa/otelgqlgen#209]
The current spans statuses are always unset. 

<img width="853" alt="image" src="https://github.com/user-attachments/assets/4e3f153a-7b99-4799-82fd-e2fe821024fa">

The spans should be finished with either 

* ok, if successful
* error, if an error was returned

This has the advantage, that spans with an error are instantly visible in tools like Grafana:

<img width="868" alt="image" src="https://github.com/user-attachments/assets/287f6542-68dd-4b64-8bc8-75a3fe4e42fc">

This could be automated.

**Comment by dkrizic** [comment]
I just see that the error is set indeed, but the Ok is not set.

**Comment by ravilushqa** [comment]
@dkrizic Good catch! Thanks for pointing this out. I’m a little bit busy at the moment but I can cover this area later. Alternatively, feel free to contribute if you’d like to address it sooner—I'd be happy to review the PR

**Comment by dkrizic** [comment]
@ravilushqa Could you please fix the pipeline on main, my PR fails as well, I just changed some go files.

**Comment by ravilushqa** [comment]
@dkrizic It looks like there's an issue with the linting stage. I'll take a look and let you know once it's fixed.

**Comment by ravilushqa** [comment]
done https://github.com/ravilushqa/otelgqlgen/pull/210
